version: "3.8"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: quotes
      MYSQL_USER: app
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 87654321
    networks:
      - laravel

  app:
    build:
      args:
        user: app
        uid: 1000
      context: ./
    container_name: quotes
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www
    networks:
      - laravel
